### ISSUE TITLE
Load example script to adapt to CosmoPower-JAX

### ISSUE THREAD

**Issue by dpiras** [cosmopower-organization/mnu#1]
Hey @HTJense @borisbolliet, 

 @Lbalkenhol would like to use some of the models here in his pipeline (particularly the neutrino ones). He was trying to open them with `CosmoPower-JAX`, and reached out to me as he was getting some errors. After some investigation I think the problem is in the format of the dictionary used to store these models.

Could you please provide an example script of how you load these models, so that I can reproduce it in `CPJ`?

Thank you!

**Comment by borisbolliet** [comment]
Yes good idea. 

See [this colab notebook](https://colab.research.google.com/drive/1YB9rUzUSKx6LeugtDU0eWRlA0yLxpM1-?usp=sharing).

(This uses the emulators loaded from `npz` files rather than `pkl`.) 

Let me know if that works and close the issue if so. If not, please let me know and we will hopefully figure it out.

**Comment by dpiras** [comment]
Thank you @borisbolliet! I will have a look at get back to you as soon as possible 👍

**Comment by dpiras** [comment]
I think I was able to adapt `CPJ` ([PR here](https://github.com/dpiras/cosmopower-jax/pull/11)) to work with the `jense_2024` models ([see here](https://github.com/cosmopower-organization/jense_2024_emulators/issues/1)), but I think something is wrong with the `mnu` models here. This is what I getting after following the notebook and adapting the `CPJ` code.
![image](https://github.com/user-attachments/assets/dcba35e7-c4ca-4f74-9e42-57ed90f74264)
![image](https://github.com/user-attachments/assets/63f05104-f407-4396-836d-f3ee4ff9619c)
![image](https://github.com/user-attachments/assets/63a769da-6af2-4463-9417-1c1bcd873c26)

What do you think @borisbolliet? TE looks reasonable, but TT and EE look wrong to me. What do you think I could have missed?

**Comment by dpiras** [comment]
Ah, I think I found the issue: this model requires `H0`, not `h` -- testing now

**Comment by dpiras** [comment]
![image](https://github.com/user-attachments/assets/1e7ec719-ff52-4c09-b126-8bcf578c721f)
![image](https://github.com/user-attachments/assets/d933a593-c9f9-4a1e-9326-6530c8cb5543)
![image](https://github.com/user-attachments/assets/52a22c90-ae81-4036-a120-4feaa70c3f65)

Seem to be working now -- if you agree I'll close both issues @borisbolliet?

**Comment by dpiras** [comment]
As a final note so that we don't forget, I'll repeat here that it would be nice to have a uniform format to save and load files in the future, so that we don't need to take into account all possible cases -- flagging this for the packaging being done [here](https://github.com/alessiospuriomancini/cosmopower/pull/28).

**Comment by borisbolliet** [comment]
This is super useful thanks @dpiras

**Comment by MinhMPA** [comment]
@borisbolliet @dpiras Hi both! Thanks a lot for making these repos public. Find them really helpful and trying to use them for the upcoming cosmology forecast and analysis for PFS.

Thanks to Boris's GoogleColab notebook, I was able to figure out, after some trial and error, how to correctly load the Fourier wavenumber for this `mnu` model

```
ls = custom_emulator.modes
custom_pk = custom_emulator..predict(custom_params_dict)

ndspl = 10
custom_k = np.geomspace(1e-4,50.,5000)[::ndspl]
dls = ls*(ls+1.)/2./np.pi
cosmopower_pk = ((dls)**-1)*(custom_pk)
```

I guess it's not high priority for you right now, but still figure it would be really helpful for others if there is an example how to load these models and their default cosmological parameter values in each `cosmopower-organization/xxx` repo. Atm, `emulator.modes` doesn't always return the Fourier wavenumber $|\vec{k}|$ (e.g. in the case above), and `emulator.predict` doesn't always return $P(k)$ directly (e.g. also this case).

**Comment by dpiras** [comment]
Thank you for pointing this out @MinhMPA! This seems to be an issue related to these particular model(s). Happy to look into it to make CosmoPower-JAX fully compatible (as I mentioned [in my PR](https://github.com/dpiras/cosmopower-jax/pull/11) this has not been thoroughly tested, as these models were developed independently from CPJ). 

If @borisbolliet can confirm how are the modes saved for these models, then I can fix this on the CPJ side. For instance, from your snippet, it's not clear how `custom_k` is used -- perhaps you could share a full script/notebook?
